### PR TITLE
"Fixed Conversion Error"

### PR DESCRIPTION
**Pull request by Vikram9866**
varables `v` and `f` are used without defining them as Signal. It causes problem during conversion.

### CODE REVIEW

**Comment by cfelton** [comment]
@Vikram9866 in general the use of "variables" is not an issue.  The changes you made are not needed.  The use of variables is convertible and synthesizable and this FIFO has been used on numerous hardware platforms.  

Can you provide more information on the error you are encountering?

**Comment by Vikram9866** [comment]
```myhdl.ConversionError: in file Fifo.py, line 91:```
```    Type mismatch with earlier assignment: v```

**Comment by cfelton** [comment]
@Vikram9866 which version of myhdl are you using?

**Comment by Vikram9866** [comment]
@cfelton Iam using this package  `myhdl-1.0dev-py2.7`

**Comment by cfelton** [comment]
@Vikram9866 this needs more investigation, this is a new conversion error with `1.0dev`.  Let me investigate when I have a little more time and when I have access to a computer to verify this is a new conversion error in 1.0 that did not exist in 0.9.

**Comment by cfelton** [comment]
@Vikram9866 I was wrong, the module failed to convert with 0.9.1 as well.  I have pushed a commit that resolves the issue using variables (not signals) and added a conversion test.

I forgot that most of my modules use `fifo_fast` (which is a sync fifo) instead of `fifo_sync`, I will need to do some more investigation to determine when/how/why `fifo_sync` broke (or maybe it was always broke).

Thanks for pointing out this issue.

**Comment by cfelton** [comment]
This was fixed via another method in the base.

**Pull request closed without merging**
