### PR TITLE
Renamed the attributes in the system/stream/FIFOBus interface.

### PR DESCRIPTION
**Pull request by forumulator**
The attributes for the cores/fifo/fifo_intf have been left unchanged, whereas all the files using the stream/FIFOBus object interface have been suitably updated.

### CODE REVIEW

**Comment by forumulator** [comment]
The Travis CI build suggest that there are still some errors, will resolve them tomorrow.

**Comment by forumulator** [comment]
Fixed errors, both the local and Travis-CI tests are passing(the errors are unrelated to renaming)

**Comment by cfelton** [comment]
Hmmm, that is odd - why is travis failing, I see that it timeout but it doesn't on the main branch so it shouldn't here.  I have had to restart (rerun it again) travis in the past, I will see if I can do that with this CI.

**Comment by cfelton** [comment]
travis is passing now and all I did was restart the test, that seems to happen often with this set of tests and I have seen it happen on other repos as well.

**Pull request merged**
